name: Book

on:
  push:
    branches:
      - release
    paths:
      - "docs/**"

jobs:
  deploy_en:
    name: Deploy book on gh-pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
      - name: Render book
        run: |
          mdbook build -d gh-pages docs/en
          mdbook build -d gh-pages docs/zh-CN
          mkdir gh-pages
          mv docs/en/gh-pages gh-pages/en
          mv docs/zh-CN/gh-pages gh-pages/zh-CN
          mv docs/index.html gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          allow_empty_commit: true
          keep_files: false
          publish_dir: gh-pages
          publish_branch: gh-pages
